Added the Footer.
Logan1x/Nucleotide-Sequence-generator pull request #7
Opened 2020-10-04 08:58 UTC by Abhishekchauhan089

@Logan1x ,  i have made the changes. Footer is added to your project

2020-10-04 09:31 UTC, Logan1x commented
Can you show me how is it looking after the update?  @Abhishekchauhan089

2020-10-04 09:51 UTC, Logan1x commented
I checked it by running locally on my machine and I want you to make some changes.
1. color scheme : Black(`#000000`) with yellow font(`#ffba08`).
2. We don't need that much content, we just need one line, `This project is an open source project, checkout our code here`(this repo hyperlink here)
3. Don't change the style.css reference in HTML code, it needed by flask to render properly.

Sorry I should've mentioned point number 1 & 2 before.

2020-10-04 09:52 UTC, Logan1x requested changes

2020-10-04 09:52 UTC, Logan1x commented on templates/index.html
> +    <link rel="stylesheet" type="text/css" href="../static/css/style.css"
need to replace it back

2020-10-04 10:16 UTC, Abhishekchauhan089 commented
@Logan1x , wait for a while.  after changing colors I will give you screenshot of the updates

2020-10-04 10:29 UTC, Abhishekchauhan089 commented
![Screenshot (3)](https://user-images.githubusercontent.com/53695727/95012951-a77a4f00-05f1-11eb-8ea4-570c95c49d49.png)

2020-10-04 10:29 UTC, Abhishekchauhan089 commented
@Logan1x , Is it okay..

2020-10-04 14:02 UTC, Logan1x commented
This is what it is looking after git pull on your repo

main page


![image](https://user-images.githubusercontent.com/10944610/95017494-39786b00-0677-11eb-9e4a-d62a70e5140d.png)

after inputting a value and submitting


![image](https://user-images.githubusercontent.com/10944610/95017500-41d0a600-0677-11eb-8863-d3c0ec13d74c.png)


When I changed color from yellow to `#ffba08` i saw the color in font and the panel for footer is taking almost half of the page. Can we minimize it to as little as we can. And remove the `nucleotide` form the footer too.

2020-10-04 14:03 UTC, Logan1x commented
Can you try running your repo with flask and then try looking at it? If you are not aware of how to do that please ask.

2020-10-04 15:17 UTC, Abhishekchauhan089 commented
@Logan1x yaa, i don't know how to run repo with flask

2020-10-04 17:06 UTC, Abhishekchauhan089 commented
@Logan1x , check this out again. i have made some changes

2020-10-04 17:07 UTC, Abhishekchauhan089 commented
![Screenshot (4)](https://user-images.githubusercontent.com/53695727/95022015-5f771e80-0629-11eb-9b24-7ec28902f977.png)

2020-10-04 17:07 UTC, Abhishekchauhan089 commented
![Screenshot (5)](https://user-images.githubusercontent.com/53695727/95022020-64d46900-0629-11eb-8ad1-5f86ac06c732.png)

2020-10-04 17:09 UTC, Abhishekchauhan089 commented
@Logan1x , I think you might like this time, i have run this repo with flask

2020-10-05 05:04 UTC, Logan1x commented
Thanks for doing so much work, I want to request one more change, Can we make the margin a bit less around 1? It feels like we are wasting so much space.

2020-10-05 05:04 UTC, Logan1x commented
And you did great job by running the repo with flask :)

2020-10-05 05:57 UTC, Abhishekchauhan089 commented
@Logan1x I have tried for the margin, little bit of changes are there, but if we force to cut the margin more. then it will we no more responsive

2020-10-05 06:38 UTC, Logan1x commented
@mrinal-27 Can you help here?

2020-10-05 06:42 UTC, mrinal-27 commented
@Logan1x  do we wanna change the margin or padding?

2020-10-05 06:44 UTC, mrinal-27 commented
> @Logan1x do we wanna change the margin or padding?

I mean, is the margin to be reduced between different elements or the padding for the footer has to be changed?

2020-10-05 06:46 UTC, Logan1x commented
I want the footer to be a bit small in height. So whatever suits the purpose.

2020-10-05 07:02 UTC, mrinal-27 commented
@Logan1x  okay I'm on it. I have never run flask before so figuring that out now.

2020-10-05 07:15 UTC, Abhishekchauhan089 commented
![Screenshot (6)](https://user-images.githubusercontent.com/53695727/95050131-e36bed80-069f-11eb-9e44-f06baeec0447.png)

2020-10-05 07:17 UTC, Abhishekchauhan089 commented
![Screenshot (7)](https://user-images.githubusercontent.com/53695727/95050245-131af580-06a0-11eb-9aaf-755bd4f88c3f.png)

2020-10-05 07:18 UTC, Abhishekchauhan089 commented
@Logan1x is it okay..?

2020-10-05 07:27 UTC, Logan1x commented
Much better than before, but if you can see there is space below the font.

2020-10-05 07:28 UTC, Abhishekchauhan089 commented
space below which font. please explain in brief

2020-10-05 07:33 UTC, Abhishekchauhan089 commented
that space below copyright?

2020-10-05 09:59 UTC, Logan1x commented
I forgot about copyright, just saw you haven't scroll down to the bottom, So I think we can remove copyright thing and just this line in center. How about that? 
This will make your work much easier.

2020-10-05 12:11 UTC, Abhishekchauhan089 commented
![Screenshot (8)](https://user-images.githubusercontent.com/53695727/95077988-44f48200-06c9-11eb-9011-23c8722a2051.png)

2020-10-05 12:33 UTC, Abhishekchauhan089 commented
![Screenshot (9)](https://user-images.githubusercontent.com/53695727/95079965-38255d80-06cc-11eb-99e8-d45737b4851c.png)

2020-10-05 12:33 UTC, Abhishekchauhan089 commented
![Screenshot (10)](https://user-images.githubusercontent.com/53695727/95079984-41162f00-06cc-11eb-803a-0356119e8870.png)

2020-10-05 12:35 UTC, Abhishekchauhan089 commented
were you saying something like this

2020-10-06 06:19 UTC, Logan1x commented
Yes, yes that's much better. Please push this to your GitHub and I'll review it.

2020-10-06 07:06 UTC, Abhishekchauhan089 commented
@Logan1x hey, i have made the PR. check it out

2020-10-06 07:20 UTC, Logan1x approved these changes

2020-10-06 07:20 UTC, merged

2020-10-06 07:20 UTC, Logan1x commented
@Abhishekchauhan089 Thank you for contributions :)

2020-10-06 15:24 UTC, Logan1x commented
@Abhishekchauhan089 The Pr is merged but the changes I see on website https://nucleotide-generator.herokuapp.com/ is bit different. 

![image](https://user-images.githubusercontent.com/10944610/95222442-1fc15a00-0816-11eb-961f-482c036cd4ed.png)

2020-10-06 15:25 UTC, Logan1x commented
And the link hyperlink doesn't contain repo link.

2020-10-06 16:34 UTC, Abhishekchauhan089 commented
actually i haven't put the repo link...you just have to put your repository link..

2020-10-06 16:34 UTC, Abhishekchauhan089 commented
you have to replace #link with your repository link